FROM registry.altlinux.org/alt/alt:p11

RUN apt-get update
RUN apt-get install -y python3 pip python3-modules-sqlite3 python3-dev gcc

COPY mysite /app

WORKDIR /app

RUN pip install -r requirements.txt

RUN python3 manage.py migrate

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
# CMD tail -F /dev/null